import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { registerSW } from "virtual:pwa-register";
import App from "./App.jsx";
import "leaflet/dist/leaflet.css";
import "./index.css";

// Auto-registers the service worker generated by vite-plugin-pwa. Silently
// updates in the background; the OfflineBanner component in the app shell
// tells the user when they are viewing cached (offline) data.
registerSW({ immediate: true });

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);
